[build]
  base = "frontend"
  publish = "out"
  command = "node build-debug.js"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NEXT_SKIP_TYPESCRIPT_AND_ESLINT_CHECKS = "1"
  NODE_ENV = "production" 