apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  uri: bW9uZ29kYjovL21vbmdvZGItc2VydmljZToyNzAxNy9zbWFydC1jaXR5 # mongodb://mongodb-service:27017/smart-city
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  secret: c21hcnRjaXR5X3NlY3JldF9rZXlfMjAyNA== # smartcity_secret_key_2024
